### ISSUE TITLE
Converting an element to a component crashes the builder

### ISSUE THREAD

**Issue by mohasarc** [codelab-app/platform#2474]
## Current Behavior

an error is thrown when converting an element to a component. after refrash, the operation seems to have been done; however, the created component is missing children.

## Video Showing Bug

https://user-images.githubusercontent.com/51242349/231744596-9214c0fc-425e-4b7c-8f96-ab9f412754b0.mp4

**Comment by amrmuhamedd** [comment]
@mohasarc 

I try with this and convertElementToComponent seem good 
some time didn't get this error what is your imagination why this error occure

https://github.com/codelab-app/platform/assets/47860740/0fb6ed7d-048b-43b1-bfd5-a6d4bc7e6695

https://github.com/codelab-app/platform/assets/47860740/0d8950c1-7b63-41bd-9948-e167935e7316

**Comment by mohasarc** [comment]
I've just tested again, and I couldn't replicate it. the issue is a little old, it could have been fixed while fixing something else.

**Comment by amrmuhamedd** [comment]
I see the error sometimes and sometimes no I think the cache may be the problem.

**Comment by mohasarc** [comment]
Oh I see, it might acutally be.

**Comment by webberwang** [comment]
From @assimhabeek: the problem here is that when converting element to component. the first thing we do is that we detachFromParent an element detached for parent doesn't have a container node (page/component). I think the best thing we can do is to make closestContainerNode Nullable and stop throwing error when closestNode is not resolved.
